// catalogue"

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_STARTED = "GET_CATEGORIES_STARTED";
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";
export const GET_CATEGORIES_SUCCEED = "GET_CATEGORIES_SUCCEED";

export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEMS_STARTED = "GET_ITEMS_STARTED";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";
export const GET_ITEMS_SUCCEED = "GET_ITEMS_SUCCEED";

export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY";

export const MORE_ITEMS = "MORE_ITEMS";

export const MAKE_QUERY = "MAKE_QUERY";

export const SET_CATEGORY = "SET_CATEGORY";
export const INCREMENT_OFFSET = "INCREMENT_OFFSET";

export const SET_URL = "SET_URL";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const POST_ORDER = "POST_ORDER";
export const POST_ORDER_STARTED = "POST_ORDER_STARTED";
export const POST_ORDER_FAILED = "POST_ORDER_FAILED";
export const POST_ORDER_SUCCEED = "POST_ORDER_SUCCEED";
